apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-store
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-store
  template:
    metadata:
      labels:
        app: frontend-store
    spec:
      containers:
        - name: frontend-store
          image: hoseki7/frontend-store:latest
          ports:
            - containerPort: 80
