apiVersion: v1
kind: Service
metadata:
  name: frontend-store
  namespace: ecommerce-hosekishops
spec:
  type: NodePort
  selector:
    app: frontend-store
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
