apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-store
  template:
    metadata:
      labels:
        app: frontend-store
    spec:
      containers:
        - name: frontend-store
          image: hoseki7/frontend-store-hosekishops:1.0
          ports:
            - containerPort: 80
