apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-store
  template:
    metadata:
      labels:
        app: frontend-store
    spec:
      containers:
      - name: frontend-store
        image: hoseki7/hosekishops-frontend-store:1.0
        ports:
        - containerPort: 80