apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: admin-panel
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
