apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: frontend-admin
        image: hoseki7/hosekishops-frontend-admin:1.1
        ports:
        - containerPort: 80
