name: CI/CD Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ================= BACKEND =================
      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-hosekishops:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-hosekishops:latest

      # ================= FRONTEND STORE =================
      - name: Build & Push Frontend Store Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-store-hosekishops:latest ./frontend-store
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-store-hosekishops:latest

      # ================= FRONTEND ADMIN =================
      - name: Build & Push Frontend Admin Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-admin-hosekishops:latest ./frontend-admin
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-admin-hosekishops:latest

      # ================= KUBERNETES DEPLOY =================
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend backend=${{ secrets.DOCKER_USERNAME }}/backend-hosekishops:latest
          kubectl set image deployment/frontend-store frontend-store=${{ secrets.DOCKER_USERNAME }}/frontend-store-hosekishops:latest
          kubectl set image deployment/frontend-admin frontend-admin=${{ secrets.DOCKER_USERNAME }}/frontend-admin-hosekishops:latest